### ISSUE TITLE
Just a thought

### ISSUE THREAD

**Issue by indirektly** [brandonmanke/node-destiny-2#12]
I've been working on a tool that finds secrets in code bases, this one still has an API key in it. It's in the history, but just because it's deleted doesn't mean it's gone. proof= https://github.com/brandonmanke/node-destiny-2/commit/dccc9130c6cc0618f0b1e91a1fc95b2e888604e7

**Comment by brandonmanke** [comment]
Hey, thanks for pointing that out! I remember accidentally committing that a while ago and I made sure to reset the key on my account and use a new one. So that one should be invalid.

**Comment by indirektly** [comment]
Ok cool, I've tested the tool with the repos of the people I follow.(not to be creepy)The Github API can in handy....
